version: "3.9"

services:
  postgres_db:
    image: postgres
    container_name: postgres_db
    environment:
      POSTGRES_DB: board
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  board_be:
    build: ./board_be
    container_name: board_be
    volumes:
      - ./board_be:/srv/board_be
    ports:
      - "8000:8000"

  board_fe:
    build: ./board_fe
    container_name: board_fe
    volumes:
      - ./board_fe:/srv/board_fe
    ports:
      - "5173:5173"
    depends_on:
      - postgres_db
      - board_be
    environment:
      - VITE_API_URL=http://localhost:8000
