# Generated by Django 5.2.1 on 2025-05-16 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prompt',
            name='default',
            field=models.BooleanField(default=False),
        ),
    ]
