# Generated by Django 5.2.1 on 2025-05-16 01:35

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompt', '0002_alter_prompt_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompt',
            name='info',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.BooleanField(), blank=True, default=list, size=None),
        ),
    ]
