# Generated by Django 5.2.1 on 2025-05-16 01:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompt', '0003_prompt_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromptFields',
            fields=[
                ('prompt_field_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('field', models.TextField()),
            ],
        ),
    ]
