# Generated by Django 5.2.1 on 2025-05-16 01:57

import uuid
from django.db import migrations, models
from core.statics.prompt import prompt_fields

def seed_prompt_fields(apps, schema_editor):
    PromptFields = apps.get_model('prompt', 'PromptFields')

    for name in prompt_fields.values():
        PromptFields.objects.create(prompt_field_id=uuid.uuid4(), field=name)

class Migration(migrations.Migration):

    dependencies = [
        ('prompt', '0004_promptfields'),
    ]

    operations = [
        migrations.RunPython(seed_prompt_fields),
    ]
