# Generated by Django 5.2.1 on 2025-05-16 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompt', '0005_create_prompt_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='promptfields',
            name='name',
            field=models.TextField(blank=True),
        ),
    ]
