# Generated by Django 5.2.1 on 2025-05-21 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prompt', '0006_promptfields_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prompt',
            name='info',
        ),
    ]
