prompt_fields = {
  'profile_name': 'profile.name',
  'profile_location': 'profile.location',
  'profile_linkedin_url': 'profile.linkedin_url',
  'profile_title': 'profile.title',
  'profile_email': 'profile.email',
  'profile_bio': 'profile.bio',
  'profile_phone': 'profile.phone',
  'profile_work_history': 'profile.work_history()',
  'profile_education_history': 'profile.education_history()',
  'job_url': 'job.url',
  'job_company': 'job.company',
  'job_title': 'job.title',
  'job_location': 'job.location',
  'job_description': 'job.description',
}