# Generated by Django 5.2.1 on 2025-05-15 09:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_alter_user_created_on_alter_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('job_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company', models.TextField(blank=True)),
                ('title', models.TextField(blank=True)),
                ('location', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('applications', models.IntegerField(blank=True)),
                ('posted_date', models.DateField(auto_now=True)),
                ('status', models.CharField(choices=[('not-applied', 'Not Applied'), ('applied', 'Applied'), ('passed', 'Passed'), ('failed', 'Failed')], default='not-applied', max_length=20)),
                ('prompt', models.TextField(blank=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
            ],
        ),
    ]
