# Generated by Django 5.2.1 on 2025-05-16 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_job_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='resume_path',
            field=models.FilePathField(blank=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='posted_date',
            field=models.DateField(blank=True),
        ),
    ]
