# Generated by Django 5.2.1 on 2025-05-18 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_alter_job_resume_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='url',
            field=models.URLField(blank=True, unique=True),
        ),
    ]
