# Generated by Django 5.2.1 on 2025-05-19 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_alter_job_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='applied_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
